ElectionTool/Models/BundeslandViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ElectionTool.Models
{
    public class BundeslandViewModel : IComparable<BundeslandViewModel>
    {
        public int Id { get; set; }

        [Display(Name = "Bundesland")]
        public string Name { get; set; }
        public int CompareTo(BundeslandViewModel other)
        {
            return Id - other.Id;
        }
    }
}

ElectionTool/Models/MessageBag.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace ElectionTool.Models
{
    public class MessageBag
    {
        public MessageBag()
        {
            Danger = new List<string>();
            Info = new List<string>();
            Success = new List<string>();
            Warning = new List<string>();
        }

        public List<string> Danger { get; set; }

        public List<string> Info { get; set; }

        public List<string> Success { get; set; }

        public List<string> Warning { get; set; }

        public MessageBag Combine(MessageBag other)
        {
            if (other == null)
                return new MessageBag
                {
                    Danger = Danger.ToList(),
                    Info = Info.ToList(),
                    Success = Success.ToList(),
                    Warning = Warning.ToList()
                };

            return new MessageBag
            {
                Danger = Danger.Concat(other.Danger).ToList(),
                Info = Info.Concat(other.Info).ToList(),
                Success = Success.Concat(other.Success).ToList(),
                Warning = Warning.Concat(other.Warning).ToList()
            };
        }

        public void Add(MessageBag other)
        {
            if (other == null)
                throw new ArgumentException("other");

            Danger.AddRange(other.Danger);
            Info.AddRange(other.Info);
            Success.AddRange(other.Success);
            Warning.AddRange(other.Warning);
        }
    }
}

ElectionTool/Models/PartyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ElectionTool.Models
{
    public class PartyViewModel : IComparable<PartyViewModel>
    {
        public int Id { get; set; }

        [Display(Name = "Partei")]
        public string Name { get; set; }

        public int CompareTo(PartyViewModel other)
        {
            return Name.CompareTo(other.Name);
        }
    }
}

ElectionTool/Models/PersonWithPartyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ElectionTool.Models
{
    public class PersonWithPartyViewModel : IComparable<PersonWithPartyViewModel>
    {
        public PersonViewModel Person { get; set; }

        public PartyViewModel Party { get; set; }

        public int CompareTo(PersonWithPartyViewModel other)
        {
            var personcomp = Person.CompareTo(other.Person);
            return personcomp != 0 ? personcomp : Party.CompareTo(other.Party);
        }
    }
}

ElectionTool/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using ElectionTool.Models;
using ElectionTool.Service;

namespace ElectionTool.Controllers
{
    public class VoteController : BaseController
    {
        // GET: Vote
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Elect(string txtToken)
        {
            var model = CallService(() => Service.ValidateToken(txtToken, Request.UserHostAddress));

            if (model != null)
            {
                return View(model);   
            }

            return RedirectToAction("Index");
        }

        public ActionResult PerformVote(ElectionVoteViewModel model)
        {
            var successful = CallService(() => Service.PerformVote(model, Request.UserHostAddress));

            if (successful)
            {
                GetMessageBag().Success.Add("Sie haben Ihre Stimme erfolgreich abgegeben.");
                return RedirectToAction("Index");
            }

            return RedirectToAction("Elect", new {txtToken = model.TokenString});
        }

        public ActionResult GenerateToken()
        {
            var model = CallService(() => Service.GetGenerateTokenModel());

            model.SelectedElectionId = TempData["ElectionId"] as int? ?? model.SelectedElectionId;
            model.SelectedWahlkreisId = TempData["WahlkreisId"] as int? ?? model.SelectedWahlkreisId;
            model.Amount = TempData["Amount"] as int? ?? model.Amount;

            return View(model);
        }

        public ActionResult GenerateTokenFor(GenerateTokenViewModel model)
        {
            CallService(() =>
            {
                TempData["ElectionId"] = model.SelectedElectionId;
                TempData["WahlkreisId"] = model.SelectedWahlkreisId;
                TempData["Amount"] = model.Amount;

                if (!model.Password.Equals("ichdarfdasschon"))
                {
                    throw new Exception("Sie dürfen mit diesem Passwort keine Token generieren.");
                }

                var election = Service.GetElection(model.SelectedElectionId);
                var wahlkreis = Service.GetWahlkreis(model.SelectedWahlkreisId);

                var infoToken = string.Format("Bundestagswahl: {0}\nWahlkreis: {1}\n\nErstellte Token:",
                    election.Date.ToShortDateString(), wahlkreis.Name);

                for (var i = 0; i < model.Amount; i++)
                {
                    infoToken += string.Format("\n    {0}",
                        TokenValidation.GenerateTokenString(model.SelectedElectionId, model.SelectedWahlkreisId));
                }

                GetMessageBag().Info.Add(infoToken);
            });

            return RedirectToAction("GenerateToken");
        }
    }
}

ElectionTool/Controllers/WahlkreisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectionTool.Controllers
{
    public class WahlkreisController : BaseController
    {
        // GET: Wahlkreis
        public ActionResult Index(int electionId)
        {
            var model = CallService(() => Service.GetWahlkreisSelection(electionId));

            return View(model);
        }

        // GET: Wahlkreis/Overview
        public ActionResult Overview(int electionId, int wahlkreisId)
        {
            var model = CallService(() => Service.GetWahlkreisOverview(electionId, wahlkreisId));

            return View(model);
        }
    }
}

ElectionTool/Controllers/WinnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectionTool.Controllers
{
    public class WinnerController : BaseController
    {
        // GET: Winner
        public ActionResult Index(int electionId)
        {
            var model = CallService(() => Service.GetWinnerWahlkreise(electionId));

            GetMessageBag().Info.Add(@"Mit <strong>Erststimme=Partei</strong> bzw. <strong>Zweiststimme=Partei</strong> kann auch nach der Siegerpartei nach Erststimmen bzw. Zweitstimmen gefiltert werden.");

            return View(model);
        }
    }
}

ElectionTool/Views/Shared/Bundesland.cshtml
@model ElectionTool.Models.BundeslandViewModel

<div class="col-md-4" style="padding-left: 0; padding-right: 0;">
    <div class="margin-top-sm" align="center">
        <img src="@string.Format("/Images/{0}.png", Model.Name)" alt="" height="22">
    </div>
</div>
<div class="col-md-8">
    @Html.DisplayFor(model => model.Name)
</div>

ElectionTool/Views/Shared/MessageBag.cshtml
@model ElectionTool.Models.MessageBag

@{
    var messageBagClass = "";
    if ((ViewBag.ShowMessagesInPlace as bool?) == false)
    {
        messageBagClass = "messagebag-message";
    }
    else
    {
        messageBagClass = "inplace-message";
    }
}

@if (Model.Danger.Any())
{
    <div class="@(messageBagClass) alert alert-danger alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul class="list-unstyled">
            @foreach (var message in Model.Danger)
            {
                <li style="white-space:pre-wrap">@Html.Raw(message)</li>
            }
        </ul>
    </div>
}

@if (Model.Warning.Any())
{
    <div class="@(messageBagClass) alert alert-warning alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul class="list-unstyled">
            @foreach (var message in Model.Warning)
            {
                <li style="white-space:pre-wrap">@Html.Raw(message)</li>
            }
        </ul>
    </div>
}

@if (Model.Success.Any())
{
    <div class="@(messageBagClass) alert alert-success alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul class="list-unstyled">
            @foreach (var message in Model.Success)
            {
                <li style="white-space:pre-wrap">@Html.Raw(message)</li>
            }
        </ul>
    </div>
}

@if (Model.Info.Any())
{
    <div class="@(messageBagClass) alert alert-info alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul class="list-unstyled">
            @foreach (var message in Model.Info)
            {
                <li style="white-space:pre-wrap">@Html.Raw(message)</li>
            }
        </ul>
    </div>
}

@{
    Model.Danger.Clear();
    Model.Warning.Clear();
    Model.Success.Clear();
    Model.Info.Clear();
}

ElectionTool/Views/Shared/Party.cshtml
@model ElectionTool.Models.PartyViewModel

<div class="col-md-7">
    @Html.DisplayFor(model => model.Name)
</div>
<div class="col-md-5">
    <div style="float: right" class="padding-left-md rectangle @string.Format("party{0}", Model.Id)"></div>
</div>

ElectionTool/Views/Shared/PersonWithParty.cshtml
@model ElectionTool.Models.PersonWithPartyViewModel
           
<div class="col-md-10">
    @Html.DisplayFor(model => model.Person.Fullname) (@Html.DisplayFor(model => model.Party.Name))
</div>
<div class="col-md-2">
    <div style="float: right" class="padding-left-md rectangle @string.Format("party{0}", Model.Party.Id)"></div>
</div>

ElectionTool/Views/Shared/_Layout.cshtml
@{
    var electionId = 0;
    
    var url = HttpContext.Current.Request.Url.AbsolutePath;
    var queryString = HttpContext.Current.Request.QueryString;

    var queryString2009 = "";
    var queryString2013 = "";

    for (var i = 0; i < queryString.Count; i++)
    {
        var key = queryString.AllKeys[i];
        var value = queryString.Get(i);

        if (key.Equals("electionId"))
        {
            int.TryParse(value, out electionId);
            
            queryString2009 = string.Format("{0}&{1}=1", queryString2009, key);
            queryString2013 = string.Format("{0}&{1}=2", queryString2013, key);
        }
        else
        {
            var add = string.Format("{0}={1}", key, value);
            queryString2009 = string.Format("{0}&{1}", queryString2009, add);
            queryString2013 = string.Format("{0}&{1}", queryString2013, add);
        }
    }

    queryString2009 = queryString2009.Length > 0 ? queryString2009.Substring(1) : queryString2009;
    queryString2013 = queryString2013.Length > 0 ? queryString2013.Substring(1) : queryString2013;

    var link2009 = string.Format("{0}?{1}", url, queryString2009);
    var link2013 = string.Format("{0}?{1}", url, queryString2013);

    var showMenu = url.StartsWith("/Home") || url.Length <= 1;
    var showSidebar = !url.StartsWith("/Vote") && !showMenu;
	
	var descriptionColSize = ViewBag.DescriptionColSize as int? ?? 12;

    var messageBag = TempData["Messages"] as ElectionTool.Models.MessageBag ?? new ElectionTool.Models.MessageBag();

    var isError = ViewBag.IsError as bool? ?? false;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ElectionTool</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/Chart.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/jq-2.1.4,dt-1.10.10/datatables.min.css"/>
</head>
<body>

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <ul class="nav navbar-nav @string.Format("{0}", showSidebar ? "padding-sidebar" : "")">
                <li class="padding-left-menu @string.Format("{0}", showMenu ? "active-menu" : "")">
                    @Html.ActionLink("Election-Tool", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </li>
                <li class="padding-left-menu @string.Format("{0}", showSidebar ? "active-menu" : "")">
                    @Html.ActionLink("Analyse", "Index", "SeatsBundestag", new {area = "", electionId = "2"}, new {@class = "navbar-brand"})
                </li>
                <li class="padding-left-menu @string.Format("{0}", !showSidebar && !showMenu ? "active-menu" : "")">
                    @Html.ActionLink("Wählen", "Index", "Vote", new {area = ""}, new {@class = "navbar-brand"})
                </li>
            </ul>
        </div>
        @if (showSidebar)
        {
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="padding-left-menu @string.Format("{0}", electionId == 1 ? "active-election": "")">
                        <a href=@link2009 class="navbar-brand">2009</a>
                    </li>
                    <li class="padding-left-menu @string.Format("{0}", electionId == 2 ? "active-election": "")">
                        <a href=@link2013 class="navbar-brand">2013</a>
                    </li>
                </ul>
            </div>
        }
    </div>
</div>
    
<!-- Content -->
<div class="container">
    <div class="row">
        @if (showSidebar)
        {
            <div class="col-md-3">
                <ol id="sidebar" class="nav nav-stacked affix well">
                    <li>@Html.ActionLink("1. Sitzverteilung im Bundestag", "Index", "SeatsBundestag", new {electionId = @electionId}, null)</li>
                    <li>@Html.ActionLink("2. Mitglieder im Bundestag", "Index", "MemberBundestag", new {electionId = @electionId}, null)</li>
                    <li>@Html.ActionLink("3. Wahlkreise", "Index", "Wahlkreis", new {electionId = @electionId}, null)</li>
                    <li>@Html.ActionLink("4. Wahlkreissieger", "Index", "Winner", new {electionId = @electionId}, null)</li>
                    <li>@Html.ActionLink("5. Überhangmandate", "Index", "Ueberhangmandate", new {electionId = @electionId}, null)</li>
                    <li>@Html.ActionLink("6. Knappste Sieger", "Index", "ClosestWinner", new {electionId = @electionId}, null)</li>
                </ol>
            </div>
        }

        <div class="@string.Format("col-md-{0}", showSidebar ? 9 : 12)">
            <div class="container body-content well">
                <div>
                    <div class="row padding-left-md">
                        <div class="col-md-12" id="messagebag">
                            @Html.Partial("MessageBag", messageBag)
                        </div>
                    </div>

                    <div class="row" style="padding-left: 20px;">
                        <div class="@string.Format("description-{0}", showSidebar ? "analysis" : "vote") @string.Format("{0}", isError ? "text-danger" : "") @string.Format("col-md-{0}", descriptionColSize)">
                            @ViewBag.Description
                        </div>
                    </div>

                    <div style="padding-left: 20px;">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<hr />
<footer></footer>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
<script src="@Url.Content("~/Scripts/default.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript" src="https://cdn.datatables.net/s/dt/jq-2.1.4,dt-1.10.10/datatables.min.js"></script>

</body>
</html>