ElectionTool/Controllers/ClosestWinnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectionTool.Controllers
{
    public class ClosestWinnerController : BaseController
    {
        // GET: ClosestWinner
        public ActionResult Index(int electionId)
        {
            var model = CallService(() => Service.GetAllPartiesForClosestWinner(electionId));

            return View(model);
        }

        // GET: ClosestWinner/Result
        public ActionResult Result(int electionId, int partyId)
        {
            var model = CallService(() => Service.GetClosestWinnerForParty(electionId, partyId));

            return View(model);
        }
    }
}

ElectionTool/Controllers/WahlkreisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectionTool.Controllers
{
    public class WahlkreisController : BaseController
    {
        // GET: Wahlkreis
        public ActionResult Index(int electionId)
        {
            var model = CallService(() => Service.GetWahlkreisSelection(electionId));

            return View(model);
        }

        // GET: Wahlkreis/Overview
        public ActionResult Overview(int electionId, int wahlkreisId)
        {
            var model = CallService(() => Service.GetWahlkreisOverview(electionId, wahlkreisId));

            return View(model);
        }
    }
}

ElectionTool/Views/ClosestWinner/Index.cshtml
@model ElectionTool.Models.PartySelectionViewModel
           
@{
    ViewBag.Title = "Parteien";
    ViewBag.Description = "Bitte wählen Sie eine Partei";
}

<div class="row">
    @foreach (var party in Model.Parties)
    {
        <div class="col-md-3">
            @Html.ActionLink(party.Name, "Result", "ClosestWinner", new {electionId = Model.ElectionId, partyId = party.Id}, new {@class = "btn btn-primary btn-block margin-top-md margin-bottom-md"})
        </div>
    }
</div>

ElectionTool/Views/ClosestWinner/Result.cshtml
@model ElectionTool.Models.ClosestWinnerForPartyViewModel

@{
    var isAllWinner = Model.ClosestWinner.All(m => m.IsWinner);

    ViewBag.Title = "Knappste Sieger";
    ViewBag.Description = string.Format("Knappste {0}: {1}", isAllWinner ? "Sieger" : "Verlierer", Model.Party.Name);

}

<div class="row margin-right-md">
    <div class="table-responsive">
        <table class="table table-striped datatable-simple">
            <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.ClosestWinner.First().Person.Fullname)</th>
                <th>@Html.DisplayNameFor(model => model.ClosestWinner.First().Wahlkreis.Name)</th>
                <th class="text-right">
                    @if (isAllWinner)
                    {
                        <span>Vorsprung</span>
                    }
                    else
                    {
                        <span>Rückstand</span>
                    }
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach (var entry in Model.ClosestWinner)
            {
                <tr>
                    <td data-order="@entry.Person.Lastname @entry.Person.Firstname">@Html.DisplayFor(_ => entry.Person.Fullname)</td>
                    <td>@Html.ActionLink(entry.Wahlkreis.Name, "Overview", "Wahlkreis", new { electionId = Model.ElectionId, wahlkreisId = entry.Wahlkreis.Id }, null)</td>
                    <td class="text-right">@Html.DisplayFor(_ => entry.Difference)</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>